import CryptoJS from 'crypto-js';

const DEFAULT_SECRET_KEY = 'hoimu_solarpunk_secure_aes_256_key_salt';

/**
 * Gets or initializes a unique encryption key stored on this device.
 * For privacy-first capabilities, we persist a high-entropy key locally,
 * which can also be viewed or re-generated by the user.
 */
let sessionMemoryKey: string | null = null;

/**
 * Gets or initializes an in-memory session encryption key.
 * Security notice: Raw keys are NEVER written to localStorage, preventing
 * XSS key extraction and browser profile compromise.
 */
export function getEncryptionKey(): string {
  if (sessionMemoryKey) return sessionMemoryKey;

  // Proactively purge legacy insecure key from localStorage if present
  if (typeof window !== 'undefined' && window.localStorage) {
    try {
      localStorage.removeItem('hoimu_aes_key');
    } catch {}
  }

  // Generate a random 256-bit high-entropy hex key in memory only
  sessionMemoryKey = CryptoJS.lib.WordArray.random(32).toString(CryptoJS.enc.Hex);
  return sessionMemoryKey;
}

/**
 * Encrypts a plaintext string using AES-256 with the specified key.
 */
export function encryptData(data: string, key: string = getEncryptionKey()): string {
  try {
    if (!data) return '';
    // AES-256-CBC with PBKDF2 salt is used when passing a string key
    const encrypted = CryptoJS.AES.encrypt(data, key).toString();
    return encrypted;
  } catch (e) {
    console.error('[Encryption] AES-256 encryption failed:', e);
    return data;
  }
}

/**
 * Decrypts an AES-256 encrypted ciphertext string.
 * Gracefully falls back to raw data if decryption fails (e.g. data was previously unencrypted).
 */
export function decryptData(encryptedStr: string, key: string = getEncryptionKey()): string {
  try {
    if (!encryptedStr) return '';
    const bytes = CryptoJS.AES.decrypt(encryptedStr, key);
    const decrypted = bytes.toString(CryptoJS.enc.Utf8);
    if (!decrypted) {
      // If result is empty, it could be that the string was stored unencrypted
      // Verify if it looks like JSON or normal string to fallback safely
      return encryptedStr;
    }
    return decrypted;
  } catch (e) {
    console.warn('[Encryption] AES-256 decryption failed, falling back to raw data:', e);
    return encryptedStr;
  }
}
