import CryptoJS from 'crypto-js';

const DEFAULT_SECRET_KEY = 'hoimu_solarpunk_secure_aes_256_key_salt';

/**
 * Gets or initializes a unique encryption key stored on this device.
 * For privacy-first capabilities, we persist a high-entropy key locally,
 * which can also be viewed or re-generated by the user.
 */
export function getEncryptionKey(): string {
  if (typeof window === 'undefined' || !window.localStorage) {
    return DEFAULT_SECRET_KEY;
  }
  let key = localStorage.getItem('hoimu_aes_key');
  if (!key) {
    // Generate a random 256-bit high-entropy hex key
    key = CryptoJS.lib.WordArray.random(32).toString(CryptoJS.enc.Hex);
    localStorage.setItem('hoimu_aes_key', key);
  }
  return key;
}

/**
 * Encrypts a plaintext string using AES-256 with the specified key.
 */
export function encryptData(data: string, key: string = getEncryptionKey()): string {
  try {
    if (!data) return '';
    // AES-256-CBC with PBKDF2 salt is used when passing a string key
    const encrypted = CryptoJS.AES.encrypt(data, key).toString();
    return encrypted;
  } catch (e) {
    console.error('[Encryption] AES-256 encryption failed:', e);
    return data;
  }
}

/**
 * Decrypts an AES-256 encrypted ciphertext string.
 * Gracefully falls back to raw data if decryption fails (e.g. data was previously unencrypted).
 */
export function decryptData(encryptedStr: string, key: string = getEncryptionKey()): string {
  try {
    if (!encryptedStr) return '';
    const bytes = CryptoJS.AES.decrypt(encryptedStr, key);
    const decrypted = bytes.toString(CryptoJS.enc.Utf8);
    if (!decrypted) {
      // If result is empty, it could be that the string was stored unencrypted
      // Verify if it looks like JSON or normal string to fallback safely
      return encryptedStr;
    }
    return decrypted;
  } catch (e) {
    console.warn('[Encryption] AES-256 decryption failed, falling back to raw data:', e);
    return encryptedStr;
  }
}
